### ISSUE TITLE
all capture* sentry middleware functions are deprecated

### ISSUE THREAD

**Issue by Zerebokep** [honojs/middleware#597]
c.get('sentry').captureException()
c.get('sentry').captureMessage()
c.get('sentry').captureEvent()
...

everything seems to be deprecated and refers to use Sentry.captureException() instead, but there is no Sentry object to import or I am missing something? The sentry examples also seem to be outdated.

**Comment by yusukebe** [comment]
Hi @Zerebokep, thanks for the issue.

@sam-lippert Can you take a look? Indeed, these methods are marked as deprecated with the `@sentry/core`. Or, the new version `v8` of Sentry SDK has been released. Should we support it?

**Comment by sam-lippert** [comment]
@yusukebe Yes, the latest version of Toucan supports Sentry v8, and this middleware should keep up to date with Toucan so that developers don't have to write their own custom middleware for new features. It looks like the Toucan version in the package.json is 3.4.0, and the latest version is 4.0.0. Is it OK if I upgrade that?

**Comment by yusukebe** [comment]
@sam-lippert 

> It looks like the Toucan version in the package.json is 3.4.0, and the latest version is 4.0.0. Is it OK if I upgrade that?

Yes!

**Comment by sam-lippert** [comment]
@yusukebe Pull request is here https://github.com/honojs/middleware/pull/620
Feel free to suggest corrections if I missed something

**Comment by yusukebe** [comment]
@Zerebokep 

Can you try the latest version of `@hono/sentry` `1.2.0`?

**Comment by Zerebokep** [comment]
Yes, it's fixed now, thank you. :)
