### ISSUE TITLE
[DENO] Zod OpenAPI, only extended class types available

### ISSUE THREAD

**Issue by 0xmosta** [honojs/middleware#606]
Trying Zod OpenAPI with deno, but noticed that types for the Hono class aren't available, only the ones extended are
 
<img width="563" alt="Screenshot 2024-07-01 at 11 54 59" src="https://github.com/honojs/middleware/assets/15924373/5e4edb46-c1ca-497c-9987-f883b020d4a6">
<img width="710" alt="Screenshot 2024-07-01 at 11 58 35" src="https://github.com/honojs/middleware/assets/15924373/039ae954-8fdf-4a7c-954b-18ef87800ed2">

Tried the same with bun/node, and it's working fine.
The same issue is happening for `z`, no methods/attributes are getting suggested when writing code/

**Comment by yusukebe** [comment]
@0xmosta 

Try to refresh the cache:

```bash
deno cache --reload main.ts
```

**Comment by 0xmosta** [comment]
> ```shell
> deno cache --reload main.ts
> ```

issue persists even after cache reload, same thing is happening on two different computers, running the latest deno version
`deno 1.44.4 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5`

**Comment by yusukebe** [comment]
@0xmosta 

This works well in my machine:

![CleanShot 2024-07-05 at 18 22 13@2x](https://github.com/honojs/middleware/assets/10682/114ae48d-0640-41f1-916b-c0b6dd406ba7)

Try to clone this repo: https://github.com/yusukebe/606

**Comment by 0xmosta** [comment]
> @0xmosta
> 
> This works well in my machine:
> 
> ![CleanShot 2024-07-05 at 18 22 13@2x](https://private-user-images.githubusercontent.com/10682/346076482-114ae48d-0640-41f1-916b-c0b6dd406ba7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAzNzQ5NDYsIm5iZiI6MTcyMDM3NDY0NiwicGF0aCI6Ii8xMDY4Mi8zNDYwNzY0ODItMTE0YWU0OGQtMDY0MC00MWYxLTkxNmItYzBiNmRkNDA2YmE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA3VDE3NTA0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNjVkZWY0YzljZjQ1NWE1ODgxMzAwZmNlYzAxMzRhMGQxYjNlOGNkNTAzZGMzY2M0MTg2NGEwZTA0N2E0NTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.cCteviLDCAWmBO40ZJYEy1aII_QgdTs82noMZbcsmJE)
> 
> Try to clone this repo: https://github.com/yusukebe/606

Tried with the provided repo, same issue.

**Comment by yusukebe** [comment]
@0xmosta 

It's weird, but I think it's not the Hono-side problem. This may be caused by the fact that they can't refer to the same `hono` package.

**Comment by elliotnash** [comment]
I was experiencing the same issue on deno 1.44.4 (also on macos: `deno 1.44.4 (release, x86_64-apple-darwin)`)
it seems to be only an lsp issue as `deno check` returned no errors. For me it only happened in IntelliJ and VSCode, and neovim with denols was fine. 

After updating to Deno 1.45.2, it seems to be fixed on all IDEs

**Comment by 0xmosta** [comment]
> I was experiencing the same issue on deno 1.44.4 (also on macos: `deno 1.44.4 (release, x86_64-apple-darwin)`) it seems to be only an lsp issue as `deno check` returned no errors. For me it only happened in IntelliJ and VSCode, and neovim with denols was fine.
> 
> After updating to Deno 1.45.2, it seems to be fixed on all IDEs

Yep, can confirm that upgrading to 1.45.2 resolved the issue, @elliotnash @yusukebe thanks.

**Comment by oscar6echo** [comment]
> After updating to Deno 1.45.2, it seems to be fixed on all IDEs

I hit the same issue in **VS Code** (using [deno extension](https://marketplace.visualstudio.com/items?itemName=denoland.vscode-deno) latest version: v3.38.0) and can state it is not linked to deno version: 1.45.1, 1.45.2, 1.45.3 work equally well.  

After experimenting it seems related to a bad reference to `hono/jsx` worsended by a cache issue.  
It appears somewhat related to https://github.com/honojs/hono/issues/2818.

The below works fine:

+ code:

```ts
// maint.ts

import { swaggerUI } from "@hono/swagger-ui";
import { createRoute, OpenAPIHono, z } from "@hono/zod-openapi";

const app = new OpenAPIHono();

app.openapi(
    createRoute({
        method: "get",
        path: "/hello",
        responses: {
            200: {
                description: "Respond a message",
                content: {
                    "application/json": {
                        schema: z.object({
                            message: z.string(),
                        }),
                    },
                },
            },
        },
    }),
    // deno-lint-ignore no-explicit-any
    (c: any) => {
        return c.json({
            message: "hello",
        });
    },
);

app.get(
    "/ui",
    swaggerUI({
        url: "/doc",
    }),
);

app.doc("/doc", {
    info: {
        title: "An API",
        version: "v1",
    },
    openapi: "3.1.0",
});

Deno.serve(app.fetch);
```
+ config:

 ```jsonc
// deno.json

{
    "imports": {
        "@hono/hono": "jsr:@hono/hono@^4.5.1",
        "@hono/swagger-ui": "npm:@hono/swagger-ui@^0.4.0",
        "@hono/zod-openapi": "npm:@hono/zod-openapi@^0.15.1"
    },
    "tasks": {
        "start": "deno run --allow-net main.ts"
    },
    "compilerOptions": {
        "jsx": "precompile",
        "jsxImportSource": "@hono/hono/jsx"
    }
}
```

But removing line ` "@hono/hono": "jsr:@hono/hono@^4.5.1",`  makes inspection fail though the code still runs:

![image](https://github.com/user-attachments/assets/770ff7b8-de77-4983-a7a3-c3482c4d722c)

To make it work again, either remove reference to `@hono/hono` from compiler options, or make it to npm instead of jsr.  

After each you change 
+ Run `deno cache --reload maint.ts` or `rm -rf .cache`  
  + **WARNING**: in my case the cache is local and `deno cache` seems to work on the cache as per `DENO_DIR` not `.vscode/settting.json`  
+ "Reload VS Code window".   

The following `deno.json` configs work:

+  ref to npm `hono/jsx`:

```json
{
    "imports": {
        "@hono/swagger-ui": "npm:@hono/swagger-ui@^0.4.0",
        "@hono/zod-openapi": "npm:@hono/zod-openapi@^0.15.1"
    },
    "tasks": {
        "start": "deno run --allow-net main.ts"
    },
    "compilerOptions": {
        "jsx": "precompile",
        "jsxImportSource": "hono/jsx"
    }
}
```

+ remove ref to   `hono/jsx`:

```json
{
    "imports": {
        "@hono/swagger-ui": "npm:@hono/swagger-ui@^0.4.0",
        "@hono/zod-openapi": "npm:@hono/zod-openapi@^0.15.1"
    },
    "tasks": {
        "start": "deno run --allow-net main.ts"
    },
    "compilerOptions": {}
}
```

**Conclusion**: Failing to reference dependency `hono/jsx` precisely breaks code inspection - which is quite annoying for users.  Maybe this could be documented in hono doc, maybe a merge of the middle ware pages for [swagger ui](https://hono.dev/examples/swagger-ui)  and [zod openapi](https://hono.dev/examples/zod-openapi) as the problem arises in VS Code when trying to use Hono properties from OpenAPIHono - not the case in either.

Anyway "Hono-on-Deno" is great ! :clap:

**Comment by oscar6echo** [comment]
I found that my setup above is very brittle :-1:   ie:
+ it breaks (ie. the Hono properties `.get`, `.fetch` are no longer found) if you do **"Deno: restart language server"** 
+ you often need do `rm -rf .cache` then **"reload window"**
+ the deno language server logs show that download stop at 1000 files
+ you cannot use **"deno.enablePaths"** to exclude folder `.cache`

After more exploration it seems that the **problem root cause is that the cache folder is inside the workspace**.  

If you :
+ remove **"deno.cache"** from `.vscode/settings/json`
+ or set it to any other location outside the workspace

Then **it works consistently** and instantly.    
No more `rm -rf cache` or "reload window" needed.  
However if you want to force things do `deno cache -c deno.json --reload main.ts`.   

(tested with version 1.45.1-2-3)

**Comment by oscar6echo** [comment]
Last point for reference:   
The observation / conclusion above holds in a corp env (behind proxy and via remote ssh) too.
