### ISSUE TITLE
[@hono/zod-openapi] Possible to infer the return type instead of explicitly defining it?

### ISSUE THREAD

**Issue by devjmetivier** [honojs/middleware#611]
I have an API that I'm porting over to Zod OpenAPI package with Hono. Looking at the docs [here](https://hono.dev/examples/zod-openapi), and in my experience, I see that it looks like the return type of the response **_must be defined_** in order to get the proper response type for the client.

Is there any way to just infer the return type when using Zod OpenAPI with Hono? This works out of the box with Hono, but I don't want to be required to validate a potentially complicated return type.

**Comment by yusukebe** [comment]
Hi @devjmetivier 

I think we should not do that. OpenAPI should define the return type explicitly using code-based schema. And it will validate types of return values. Or how about don't write the `response` field?

**Comment by devjmetivier** [comment]
@yusukebe I think the `response` field is required and I would otherwise get a TS error. After I wrote this I think I realized that explicitly defining the return type/shape is part of the spec.

**Comment by Blankeos** [comment]
Bringing this up again. I'm trying to take advantage of both Hono RPC + OpenAPI. Which is a bit difficult when the explicit `response` spec is involved.

Is it possible to just not pass the `response` field? It seems to require it.

---

In ElysiaJS for instance, I can explicitly define the request `params` and `body` which I think is the most useful because it actually validates. But I personally wouldn't think too much about the response type and don't really have a need to validate it. It just feels like a pain to explicitly define it for every route.

<img width="1706" alt="image" src="https://github.com/honojs/middleware/assets/38070918/b5aaeea1-987d-4f67-b4b4-2c6a0d52d018">

This way I can easily view the API docs on the browser but also infer the types using Elysia's client (Eden).

Wondering if I could do something similar in Hono?

**Comment by yusukebe** [comment]
@Blankeos 

This means that using a "normal RPC" is not enough since you want to have API docs like OpneAPI?

**Comment by Blankeos** [comment]
I mean, it's enough. It would just be nice to have both the **return type RPC** and OpenAPI.

Regular RPC-mode feels really nice to just write typescript and get types inferred automatically.

I personally use OpenAPI to just add small descriptions + an explorable and testable UI for the API. I agree with OP's sentiments on complex return types (I don't need to validate it).

It would be nice if `responses` was undefined, the api's return type would just default to the handler's return type just like in regular Hono RPC-mode.

**Comment by yusukebe** [comment]
@Blankeos 

> It would be nice if `responses` was undefined, the api's return type would just default to the handler's return type just like in regular Hono RPC-mode.

If `responses` is undefined, are you okay with it not documenting response definitions?

**Comment by Blankeos** [comment]
Thanks @yusukebe! Appreciate you for considering. 

In any case, I kind of played around with the source code for the `@hono/zod-openapi` package. I got the types working for what I needed. I'm using a separate `.openapi` that ignores the Route Config's response DTO for now.

<img width="470" alt="image" src="https://github.com/honojs/middleware/assets/38070918/625bea5c-99ec-4cbb-aece-6a9d6f1c9cb7">

I'll post a link to a fork later maybe if I polish it up.

**Comment by yusukebe** [comment]
Hi @Blankeos 

The `openapiNoResponse` is interesting! I want to use it and see the code.
